name: Service CI - Go

# Template CI workflow for Go services
# Copy this file to ci-<service-name>.yml and adjust the working-directory

on:
  push:
    branches: [ main ]
    paths:
      - 'generated_implementation/<SERVICE_PATH>/**'
  pull_request:
    branches: [ main ]
    paths:
      - 'generated_implementation/<SERVICE_PATH>/**'
    
jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: generated_implementation/<SERVICE_PATH>
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
          cache-dependency-path: generated_implementation/<SERVICE_PATH>/go.sum
      - name: Install dependencies
        run: go mod download
      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          working-directory: generated_implementation/<SERVICE_PATH>
          args: --timeout=5m
      - name: Test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...
        
  build:
    runs-on: ubuntu-latest
    needs: test
    defaults:
      run:
        working-directory: generated_implementation/<SERVICE_PATH>
    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'
          cache: true
          cache-dependency-path: generated_implementation/<SERVICE_PATH>/go.sum
      - name: Install dependencies
        run: go mod download
      - name: Build
        run: go build -v ./...
