name: CI Legacy (See meta-ci.yml)

# This file is kept for backward compatibility but should be replaced by meta-ci.yml
# and implementation CI in the generated_implementation/.github/workflows directory.

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
jobs:
  redirect:
    runs-on: ubuntu-latest
    steps:
      - name: Redirect Notice
        run: |
          echo "This workflow is deprecated in favor of the new meta/implementation separation."
          echo "Please use meta-ci.yml and implementation-ci.yml instead."
          exit 0
